---
title: Getting started with GUIs
hero_image: images/banner.png
description: Make simple graphic user interfaces in Python
original_url: https://raspberrypi.org/learning/getting-started-with-guis
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: What is a GUI?
- title: Getting started
  completion:
  - engaged
- title: Adding widgets
- title: Text widget
- title: TextBox widget
- title: PushButton widget
- title: Slider widget
- title: Picture widget
- title: Review
- title: A new app
- title: Combo widget
- title: CheckBox widget
- title: ButtonGroup widget
- title: Finishing the program
  completion:
  - internal
- title: What next?
